### PR TITLE
Fixes #22359: Make parsing "process" in inventory optional

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/22359

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Do we need an change in rudder-upgrade to add it to existing config file ? there is a fallback but maybe

**Review by VinceMacBuche — APPROVED** [review]

**Comment by VinceMacBuche** [comment]
no need to have it in rudder-upgrade

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
OK, squash merging this PR

**Pull request merged**
