### PR TITLE
Fixes #20281: Query seems to be ignored for pendings nodes

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/20281

### CODE REVIEW

**Comment by ncharles** [comment]
tests are broken

**Comment by ncharles** [comment]
PR updated with a new commit

**Review by fanf — APPROVED** [review]

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Pull request merged**
