### PR TITLE
Fixes #7310: refactor promise writting logic

### PR DESCRIPTION
**Pull request by fanf**
Ref: https://www.rudder-project.org/redmine/issues/7310
Main things are:

-  cleanly separate and enumarate in a for loop the different steps of the "write promises" part
-   remove the different *CF3FilePromiseWriterService
-   merge RudderCf3PolicyDraft and Cf3PolicyDraft
-   put everyting dealing with removing technique from node in nodeConfigurationServie.sanitize
-   clean a lot Cf3PromisesFileWriterService
-   simplify and make immutable Cf3PromiseContainer
-   remove some unused tests
-   Put eventlogrepos with eventlogs (just a move)

Update and replace https://github.com/Normation/rudder/pull/921

### CODE REVIEW

**Comment by ncharles** [comment]
could you merge all commits and correct their names ?

**Comment by fanf** [comment]
PR updated

**Comment by ncharles** [comment]
this is a great improvement ! thank you !

**Comment by ncharles** [comment]
merging !

**Pull request merged**
