### PR TITLE
Fixes #20497: We can save a technique with a missing component name for a nested block

### PR DESCRIPTION
**Pull request by ElaadF**
https://issues.rudder.io/issues/20497

### CODE REVIEW

**Comment by ElaadF** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Comment by ElaadF** [comment]
OK, squash merging this PR

**Comment by ElaadF** [comment]
OK, squash merging this PR

**Comment by ElaadF** [comment]
OK, squash merging this PR

**Pull request merged**
