### PR TITLE
Fixes #20683: Rewrite the API account page in Elm

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/20683

### CODE REVIEW

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
PR rebased

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Review by ElaadF — APPROVED** [review]

**Pull request merged**
