### PR TITLE
Fixes #19246: Clean workspace at the end of Rust builds and add licence artifacts

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/19246

### CODE REVIEW

**Comment by amousset** [comment]
Don't merge, testing stuff for now

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Comment by amousset** [comment]
OK, squash merging this PR

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
