### PR TITLE
Fixes #25116: Add parameter to change maximum limit on a quicksearch

### PR DESCRIPTION
**Pull request by ElaadF**
https://issues.rudder.io/issues/25116

### CODE REVIEW

**Comment by ElaadF** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by ElaadF** [comment]
PR rebased

**Comment by ElaadF** [comment]
Commit modified

**Comment by ElaadF** [comment]
Commit modified

**Comment by ElaadF** [comment]
PR replaced by https://github.com/Normation/rudder/pull/5778

**Pull request closed without merging**
