### PR TITLE
Fixes #25148: Rudderc fails to render "plain" variables on Windows

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/25148

### CODE REVIEW

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Review by amousset — APPROVED** [review]

**Comment by Fdall** [comment]
OK, squash merging this PR

**Pull request merged**
