### PR TITLE
Fixes #24226: rudderc canonifies already canonified condition expression resulting in loss of logic operators such as ) and |

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/24226

### CODE REVIEW

**Comment by Fdall** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
if_condition and unless_condition are only used here. You should fix the methods instead of duplicating them

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
OK, squash merging this PR

**Pull request merged**
