### PR TITLE
Fixes #7910: Missing usefull logger in logger file

### PR DESCRIPTION
**Pull request by fanf**
https://www.rudder-project.org/redmine/issues/7910

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Need rebase :(

**Comment by VinceMacBuche** [comment]
Else ok and can be self merged!

**Comment by VinceMacBuche** [comment]
ping @fanf for rebase :)

**Comment by fanf** [comment]
PR replaced by https://github.com/Normation/rudder/pull/1058

**Pull request closed without merging**
