### PR TITLE
Fixes #6073: Compute compliance asynchronously when dispalying Rule page

### PR DESCRIPTION
**Pull request by VinceMacBuche**

### CODE REVIEW

**Comment by fanf** [comment]
Something does not work as expected here, but I don't know what for now. I don't see real async computation for compliance, and switching from page to page on the rule grid takes ages (10s ?) with lots of CPU used (one core 100%). 
So, I'm going to try to find more information on that.

**Comment by VinceMacBuche** [comment]
Activate the debug logger, you will see what is taking you so much time

**Comment by VinceMacBuche** [comment]
@fanf updated !

**Comment by fanf** [comment]
Now, that's nice !

**Pull request merged**
