### PR TITLE
Fixes #18197: pending changes of resources (files deleted / modified / added ) are commited automatically during upgrade

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/18197

### CODE REVIEW

**Comment by fanf** [comment]
Actually, I think that it's what we want. What could be a reason other than "some action was interrupted" to have uncommited files in these directories ?

**Comment by VinceMacBuche** [comment]
we were editing and we did not save, this is why we have uncommitted files

**Comment by fanf** [comment]
ok.
I think we must find way to avoid that case, it's an UI nightmare. Perhaps we should just commit file when they are uploaded. Or delete them if not saved and moving away (with a pop-up "there is uncommited resources, what to do? Delete or save ?").

**Review by fanf — APPROVED** [review]

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Pull request merged**
