### PR TITLE
Fixes #16749: rl turn ptypes into pvalues to have more informations of variables stored

### PR DESCRIPTION
**Pull request by gpoblon**
https://issues.rudder.io/issues/16749

### CODE REVIEW

**Comment by gpoblon** [comment]
Had a hard time compiling everything, but it is working and passes all standard tests. Will need a doublecheck and some debug to make sure it stores types/values as intended.

**Comment by peckpeck** [comment]
Ok for me

**Comment by peckpeck** [comment]
@gpoblon rebase needed

**Comment by gpoblon** [comment]
Should be mergable

**Comment by peckpeck** [comment]
OK, merging this PR

**Pull request merged**
