### PR TITLE
Fixes #14685: Add shellcheck linting to shell scripts in the rudder repo

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/14685

### CODE REVIEW

**Comment by amousset** [comment]
Commit modified

**Comment by peckpeck** [comment]
we need first to ensure that shellcheck is installed on merger machines and on the CI

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
