### PR TITLE
Fixes #25438: The severity ERROR for Node with ID ‘xxx’ was not found in Rudder’ is too strict

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/25438

### CODE REVIEW

**Review by clarktsiory — COMMENTED** [review]
LGTM for the current changes but there is still [a missing change](https://github.com/Normation/rudder/blob/branches/rudder/8.1/webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala#L181) that makes it still log an error for the `/api/nodes/{nodeid}` : 
```
ERROR com.normation.rudder.rest.RestUtils - "An error was encountered when looking for node with ID 'unknown-node': Inconsistency: Node is missing"
```

This one will be removed once it is not used anymore (the endpoint is migrated to zio-json in 8.2)

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
It's corrected

**Review by clarktsiory — APPROVED** [review]
LGTM !

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
