### PR TITLE
Fixes #16283: we are always computing compliance and byNodes on RuleStatusReport, even when it's not necessay

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/16283

### CODE REVIEW

**Comment by fanf** [comment]
this one will not go in 5.0.15

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
once 6.0.4 is released, we should be able to merge that

**Comment by ncharles** [comment]
rejected in favor for https://github.com/Normation/rudder/pull/2754/files

**Pull request closed without merging**
