### PR TITLE
Fixes #24515: Rudder should finish to migrate all techniques when booting instead of stopping on first error

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/24515

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Commit modified

**Review by fanf — APPROVED** [review]
Lgtm!

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Pull request merged**
