### PR TITLE
Fixes #22659: Remove heartbeat configuration from the settings

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/22659

### CODE REVIEW

**Comment by RaphaelGauthier** [comment]
There are still references to the Hearbeat configuration in the back-end code. I don't know if we should get rid of them too

**Comment by amousset** [comment]
We should but in 8.0.

**Review by VinceMacBuche — APPROVED** [review]

**Comment by VinceMacBuche** [comment]
Did you try to save an heartbeat mode without value defined ?

**Review by VinceMacBuche — APPROVED** [review]

**Comment by RaphaelGauthier** [comment]
We can no longer change the heartbeat mode, saving works fine without a heartbeat value

**Comment by VinceMacBuche** [comment]
Yes sorrty i meant "changes-only" but the api still needs a value, but you set it in fact (to 1) so it should be ok

**Comment by VinceMacBuche** [comment]
(and i accepted the pr when i realised it but it does not merge :( )

**Pull request merged**
