### PR TITLE
Fixes #18484: update backtrace with better performance in parser

### PR DESCRIPTION
**Pull request by gpoblon**
https://issues.rudder.io/issues/18484

### CODE REVIEW

**Comment by gpoblon** [comment]
PR updated with a new commit

**Comment by gpoblon** [comment]
PR updated with a new commit

**Comment by gpoblon** [comment]
Commit modified

**Comment by gpoblon** [comment]
PR rebased

**Comment by gpoblon** [comment]
Commit modified

**Review by peckpeck — APPROVED** [review]

**Pull request merged**
