### PR TITLE
Fixes #24205: Pylint test fails with an exception

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/24205

### CODE REVIEW

**Comment by Fdall** [comment]
Commit modified

**Review by fanf — APPROVED** [review]

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
OK, squash merging this PR

**Comment by Fdall** [comment]
OK, merging this PR

**Comment by Fdall** [comment]
OK, merging this PR

**Pull request merged**
