### PR TITLE
Fixes #17614: fix doc configuration files

### PR DESCRIPTION
**Pull request by gpoblon**
https://issues.rudder.io/issues/17614

### CODE REVIEW

**Comment by amousset** [comment]
Could you make doc tests work?

**Comment by amousset** [comment]
IIRC the commands used in the makefile to test doc file is not correct, parameters have been renamed.

**Comment by gpoblon** [comment]
Yes, I am working on it but I discovered another issue fixing this one

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
