### PR TITLE
Fixes #25545: Techniques no longer compile with error in rudderc arguments

### PR DESCRIPTION
**Pull request by clarktsiory**
https://issues.rudder.io/issues/25545

Command line parameters are supposed to be non empty. 
`args` is a list of params and not a single string one

### CODE REVIEW

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
Can you update https://github.com/Normation/rudder/blob/branches/rudder/8.2/webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_error/1.0/compilation-config.yml with what would be a correct arg in yml file?

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Review by fanf — APPROVED** [review]
It works as wanted :+1:

**Comment by clarktsiory** [comment]
OK, squash merging this PR

**Pull request merged**
