### PR TITLE
Fixes #20239: Rocky Linux is not recognized

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/20239

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
It misses a logo like we have for most OS, maybe @RaphaelGauthier  Could give you the correct one ?

**Comment by ncharles** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Comment by ncharles** [comment]
PR updated with a new commit

**Comment by ncharles** [comment]
OK, squash merging this PR

**Pull request merged**
