### PR TITLE
Fixes #24568: Disabled plugins are enabled when upgrading to 8.1

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/24568

### CODE REVIEW

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Comment by VinceMacBuche** [comment]
OK, squash merging this PR

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Pull request merged**
