### PR TITLE
Fixes #23049: Wrong command to call rudderc in webapp

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/23049

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
If there's no more need for Unix only, we will be able to simplify even more things latter.

Lgtm!

**Review by fanf — APPROVED** [review]

**Pull request merged**
