### PR TITLE
Fixes #15752: Merge inventory endpoint and rudder webapps

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/15752

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Don't you have also project inventory-edpoint to delete too ?

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR rebased

**Comment by fanf** [comment]
OK, merging this PR

**Pull request merged**
