### PR TITLE
Fixes #18851: Allow verifying upstream server certificate when forwarding files

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/18851

### CODE REVIEW

**Comment by amousset** [comment]
Still some stuff to fix.

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
We are missing HTTP client replacement at config reload

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Pull request merged**
