### PR TITLE
Fixes #17802: shared-files acls are incorrect on relays

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/17802

### CODE REVIEW

**Comment by peckpeck** [comment]
what does this directory contain on relays ?

**Comment by Fdall** [comment]
The synchronized shared-files from the root server.

**Comment by peckpeck** [comment]
This can be very expensive on a big relay, do we really need -R ?

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
OK, squash merging this PR

**Pull request merged**
