### PR TITLE
Fixes #18849: Save button moves when switching of compliance reporting mode

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/18849

### CODE REVIEW

**Comment by RaphaelGauthier** [comment]
PR rebased

**Comment by RaphaelGauthier** [comment]
PR rebased

**Review by fanf — APPROVED** [review]

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Pull request merged**
