### PR TITLE
Fixes #20283: Missing elm 0.19.1 in 7.0 tests

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/20283

### CODE REVIEW

**Review by VinceMacBuche — APPROVED** [review]

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
