### PR TITLE
Fixes #20395: css of generation status is dubious in 7.0

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/20395

### CODE REVIEW

**Comment by RaphaelGauthier** [comment]
css-nav-notification

**Comment by VinceMacBuche** [comment]
Awesome, what does the status look like when a generation is in progresse ? used to be blue

also what does the error status look like ?  (i imagine like healthceck)

**Comment by VinceMacBuche** [comment]
From what I read in the PR you did it !

**Comment by amousset** [comment]
Awesome

**Comment by RaphaelGauthier** [comment]
Here is the different states :
bg-status

**Pull request merged**
