### PR TITLE
Fixes #18768: Node name not visible in node configuration screen

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/18768

### CODE REVIEW

**Review by VinceMacBuche — APPROVED** [review]

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Pull request merged**
