### PR TITLE
Fixes #15646: Memory Leak in Rudder 5.0

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/15646

### CODE REVIEW

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by fanf** [comment]
This is maybe a Scala bug, tracked here: https://github.com/scala/bug/issues/11727

**Pull request merged**
