### PR TITLE
Fixes #23929: Display compliance score in the Node summary tab

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/23929

We are introducing a new visual representation of a node's compliance score in Rudder. This score and its details displayed in the node's Summary tab.

The first elm app is used to display the compliance score, while the second is currently only used to display the score details, but will be used at a later date to display all the other contents of the Summary tab when the API allows it.

All the CSS relating to the compliance score has been written to the rudder-progress-bar.scss file, which has been renamed rudder-compliance.scss.

Preview : 
compliance-score-v2

Without compliance : 
no-compliance-display

### CODE REVIEW

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
PR updated with a new commit

**Comment by RaphaelGauthier** [comment]
PR updated with a new commit

**Comment by RaphaelGauthier** [comment]
PR rebased

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Pull request merged**
