### PR TITLE
Fixes #22731: Rudder-plugin-glpi sends inventory of node that no longer exists

### PR DESCRIPTION
**Pull request by peckpeck**
https://issues.rudder.io/issues/22731

### CODE REVIEW

**Comment by ncharles** [comment]
some user want to keep their old inventory for auditing purpose - by doing that you deny this possibility by default and induce a change in a patch release

**Comment by peckpeck** [comment]
Isn't that what the /var/rudder/inventories/historical directory is for ?

**Comment by ncharles** [comment]
i'm unsure ? plus, this doesn't exist anymore in 8.0

**Comment by peckpeck** [comment]
i still have this directory in rudder 8.0.4

**Comment by peckpeck** [comment]
replaced by https://github.com/Normation/rudder-plugins/pull/666

**Pull request closed without merging**
