### PR TITLE
Fixes #17724: error about rudder lang in logs

### PR DESCRIPTION
**Pull request by gpoblon**
https://issues.rudder.io/issues/17724

### CODE REVIEW

**Comment by gpoblon** [comment]
first commit contains changes;
second commit only contains rights modifications for testing purposes

**Comment by amousset** [comment]
A lot of text files are unnecessarily made executable by this PR

**Comment by gpoblon** [comment]
fixed (forced push fixup)

**Comment by gpoblon** [comment]
another fix incoming

**Comment by peckpeck** [comment]
OK, squash merging this PR

**Pull request merged**
