### PR TITLE
Fixes #18272: Optionally accept node with same hostname as an already accepted one 

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/18272

### CODE REVIEW

**Comment by amousset** [comment]
you are changing hook permissions, is it intended?

**Comment by fanf** [comment]
No, good catch. Normaly I have a test on that, but it didn't caught it :( Thanks

**Comment by fanf** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
