### PR TITLE
Fixes #19537: Add Kali Linux to the list of recognized OS

### PR DESCRIPTION
**Pull request by ElaadF**
https://issues.rudder.io/issues/19537

 - [x] Kali icon
 - [x] ${node.inventory[os][name]} = Kali
 - [x] Name in tooltip info = Kali
 - [x] OS enum in api-doc

### CODE REVIEW

**Comment by ElaadF** [comment]
Commit modified

**Review by fanf — COMMENTED** [review]
you need to add:

- an entry for kali in `rudder-node.css` (around line 270) for kali logo in node details, 
- the logo at the corresponding place, 
- an entry in `os.yml` for api doc

Appart from that, seems OK. Did you checked with an other added distro (like scientific) PR if everything is there ?

**Comment by fanf** [comment]
I looked for amazon linux, and you seems to have all the case covered.

**Comment by ElaadF** [comment]
Commit modified

**Comment by ElaadF** [comment]
Commit modified

**Review by VinceMacBuche — APPROVED** [review]

**Pull request merged**
