### PR TITLE
Fixes #18363: Add check name in healthcheck API

### PR DESCRIPTION
**Pull request by ElaadF**
https://issues.rudder.io/issues/18363

### CODE REVIEW

**Comment by ElaadF** [comment]
Commit modified

**Review by VinceMacBuche — APPROVED** [review]

**Comment by amousset** [comment]
Could you also update the API doc?

**Comment by VinceMacBuche** [comment]
Do it in this PR Elaad

**Comment by ElaadF** [comment]
Commit modified

**Pull request merged**
