### PR TITLE
Fixes #21180: Improve elm build consistency with plugins

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/21180

### CODE REVIEW

**Review by VinceMacBuche — CHANGES_REQUESTED** [review]
You need to rename in html files the path the js file is the generated file has changed

**Comment by amousset** [comment]
I did not rename anything in Rudder, only in plugins

**Comment by amousset** [comment]
But previous PR introduced a bug by adding `.min.`

**Review by VinceMacBuche — APPROVED** [review]

**Comment by VinceMacBuche** [comment]
I misread the cp command, mon mauvais :felisk:

**Pull request merged**
