### PR TITLE
Fixes #23948: Remove early return to prepare to Scala3 migration in box sequence/traverse

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/23948

This is a backport in 7.3 for #5276

### CODE REVIEW

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by mbaechler** [comment]
nice

**Review by clarktsiory — APPROVED** [review]
LGTM !

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
