### PR TITLE
Fixes #24456: Missing primary key statement for user sessions table creation when migrating

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/24456

What is in the migration and in SQL is not synched. We need to find a way to make it synched, else we will have things like that all the time. 

So:
- correct the initial migration of the table
- add a bit of script to add primary relation if it doesn't exists

### CODE REVIEW

**Review by clarktsiory — APPROVED** [review]
LGTM !

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
