### PR TITLE
Fixes #22179: Make rudderc techniques work in edge cases

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/22179

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by Fdall — APPROVED** [review]

**Pull request merged**
