### PR TITLE
Fixes #18681: Inherited properties always displayed in the column, even if checkbox unchecked

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/18681

### CODE REVIEW

**Comment by fanf** [comment]
I think that doesn't handle the case where you add two times the same property, one with inherited, the other with non inherited mode. 
In that case, after a reload (not just after adding the column), both column will show inherited values

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Review by fanf — APPROVED** [review]

**Comment by VinceMacBuche** [comment]
OK, squash merging this PR

**Pull request merged**
