### PR TITLE
Fixes #24317: Use bootstrap variables to define the default text size and font

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/24317

### CODE REVIEW

**Review by amousset — APPROVED** [review]

**Comment by amousset** [comment]
@RaphaelGauthier rebase required

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Comment by RaphaelGauthier** [comment]
PR rebased

**Comment by fanf** [comment]
The real commit for that PR is: commit:fff5384a45588c3e49426b2a0c2144d486ffe1ad

**Pull request merged**
