### PR TITLE
Fixes #18590: Rename node menu entries for consistency

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/18590

### CODE REVIEW

**Review by VinceMacBuche — APPROVED** [review]

**Comment by VinceMacBuche** [comment]
I think there is also the title of the pages to change

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
I was doing *exactly* that

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
