### PR TITLE
Fixes #6323: Missing rule and group category ID

### PR DESCRIPTION
**Pull request by fanf**
I'm not sure it should go in 2.10, but perhaps only in 3.0 ?

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Or it's a bug and it should be merged in 2.10 or it's a feature and should be merged on master

This is so lame that we do not display that information, and it will force people to make ldap requests on their server which we do not want ...

**Comment by fanf** [comment]
OK, could you please double check that only displaying is impacted, and that "things run as expected" with that ?

**Comment by VinceMacBuche** [comment]
I'm on it!

**Comment by VinceMacBuche** [comment]
This works fine! I'm merging it I think it will really help our users!

**Pull request merged**
