### PR TITLE
Fixes #25203: The pending nodes API now returns array of arrays of nodes instead of an array of nodes

### PR DESCRIPTION
**Pull request by ElaadF**
https://issues.rudder.io/issues/25203
image

### CODE REVIEW

**Comment by ElaadF** [comment]
Commit modified

**Comment by fanf** [comment]
Seems ok, can you add an unit test in `node_api.yml` so that we don't get bitten by that again?

**Review by fanf — CHANGES_REQUESTED** [review]
Seems ok, can you add an unit test in node_api.yml so that we don't get bitten by that again?

**Comment by ElaadF** [comment]
See https://github.com/Normation/rudder/pull/5799#pullrequestreview-2227352345

**Pull request closed without merging**
