### PR TITLE
Fixes #23547: Remove technique.json and rudder_reporting.cf when migrating technique to new format

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/23547

### CODE REVIEW

**Review by fanf — APPROVED** [review]
Lgtm, the file are just added to the commit list (we should never delete a json directly, always migrate it, but here, it was migrated and just need to be commited)

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
PR rebased

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
