### PR TITLE
Fixes #24498: There is no easy way to copy a property/inventory variable name to clipboard

### PR DESCRIPTION
**Pull request by ElaadF**
https://issues.rudder.io/issues/24498
V2 (last edit)
copy-to-clipboard-v2

-----------------
property_clipboard
image
image
image
image
image

### CODE REVIEW

**Comment by ElaadF** [comment]
PR rebased

**Comment by ElaadF** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
I think the copy icon should be in gray like in technique editor copy. 

In edit mode you should change the colspan of edition column to 2 and remove the copy column so that it takes the whole space in this case

**Comment by ElaadF** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Comment by ElaadF** [comment]
OK, squash merging this PR

**Pull request merged**
