### PR TITLE
Fixes #25293: API documentation for user management in 8.2

### PR DESCRIPTION
**Pull request by clarktsiory**
https://issues.rudder.io/issues/25293

This also needs changes from https://github.com/Normation/rudder/pull/5808

### CODE REVIEW

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by clarktsiory** [comment]
PR rebased

**Review by fanf — APPROVED** [review]
Lgtm

**Pull request merged**
