### PR TITLE
Fixes #12735: Unused formatter in policy generation spend a bit of time in policy generation

### PR DESCRIPTION
**Pull request by ncharles**
https://www.rudder-project.org/redmine/issues/12735

### CODE REVIEW

**Comment by fanf** [comment]
That makes me happy :)

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Pull request merged**
