### PR TITLE
Fixes #17594: no policy generation after accepting many nodes in 6.1

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/17594

### CODE REVIEW

**Comment by ncharles** [comment]
need testing

**Comment by ncharles** [comment]
this is invalid: last policy generation is doubled

**Comment by fanf** [comment]
This produces a double generation when all nodes are accepted, but the only real solution would be to have a time buffer before triggering generation - not what we can do in a minor.

**Comment by ncharles** [comment]
PR updated with a new commit

**Comment by ncharles** [comment]
i don't have double generation anymore with that, and it's much cleaner to have a way to force dynamic group update when requested

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
