### PR TITLE
Fixes #21875: Update Rust for 7.3

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/21875

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
