### PR TITLE
Fixes #21157: Huge broken logs in relayd

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/21157

### CODE REVIEW

**Comment by amousset** [comment]
PR rebased

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
Once it's ready for review, can you explain the cause of the problem and the implemented solution in pr description please?

**Comment by amousset** [comment]
There is already a link to the explanation in the ticket, but I'll add details to the PR too.

**Comment by fanf** [comment]
> There is already a link to the explanation in the ticket, but I'll add details to the PR too.

Yes, qualification/analyse of cause in the ticket is great, here it's more how the solution translates to code

**Pull request merged**
