### PR TITLE
Fixes #10386: Bad Rudder logo in src/main/webapp/images

### PR DESCRIPTION
**Pull request by fanf**
https://www.rudder-project.org/redmine/issues/10386

### CODE REVIEW

**Comment by fanf** [comment]
PR rebased

**Comment by amousset** [comment]
Where is it used? We are moving from a small logo to a very big one.

**Comment by VinceMacBuche** [comment]
I don't think it's used anymore

**Comment by fanf** [comment]
It' used in the doc.

**Comment by fanf** [comment]
I'm ok to remove it completelly and add it in the doc directly (or use in the doc an other already present)

**Comment by amousset** [comment]
Which doc? All images should be embedded in the rudder-doc folder.

**Comment by fanf** [comment]
The first, main image of old doc (in html) is taken from rudder repository.

**Comment by amousset** [comment]
This doc is not embedded nor linked anywhere starting from 4.0. Anyway, we should probably remove it and use an icon directly in the rudder-doc repo.

**Comment by fanf** [comment]
OK, I'm removing the logo from rudder repos 4.0 and up. It will most likelly breaks the doc build, and so doc "html" target should be removed or the image embeded.

**Comment by fanf** [comment]
PR rebased

**Comment by amousset** [comment]
It is also in the doc repo, I don't think this one is used anywhere https://github.com/Normation/rudder-doc/blob/master/style/html/logoRudder.jpg

**Pull request merged**
