### PR TITLE
Fixes #20708: Replacement of the screenshot in the README

### PR DESCRIPTION
**Pull request by julienbriault**
https://issues.rudder.io/issues/20708

### CODE REVIEW

**Review by amousset — APPROVED** [review]

**Review by VinceMacBuche — APPROVED** [review]

**Review by ncharles — CHANGES_REQUESTED** [review]
it has a ${version} rather than the correct version

**Comment by julienbriault** [comment]
PR updated with a new commit

**Comment by julienbriault** [comment]
PR updated with a new commit

**Comment by julienbriault** [comment]
PR rebased

**Pull request merged**
