### PR TITLE
Fixes #6381: File /var/log/rudder/compliance/non-compliant-reports.log is not correctly rotated

### PR DESCRIPTION
**Pull request by fanf**
This ticket only add the log rotation from logback. We still need to remove the log rotation done by logrotate, and the two pull request must be merged together.

### CODE REVIEW

**Comment by ncharles** [comment]
Looks good to me !

**Comment by fanf** [comment]
I added /var/log/rudder/core/rudder-webapp.log, because it is in exactly the same case.

**Comment by ncharles** [comment]
@fanf : these are 2 completely different cases. the rudder-web logs are not causing any issue for the moment, as they are not logrotated. However, they are gziped by rudder-agent

**Comment by fanf** [comment]
I'm not talking about /var/log/rudder/webapp/xxxx.sterrout.log. But closing that PR because it should target 2.10

**Pull request closed without merging**
