### PR TITLE
Fixes #15382: Generate a bundle for each directive so it can be called with one bundle

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/15382

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by fanf** [comment]
That's OK for me, just need to remove "." in bundle name.
I find the resulting "rudder directive sequence" much more easy to understand, that's really good!

**Comment by VinceMacBuche** [comment]
Commit modified

**Pull request merged**
