### PR TITLE
Fixes #19468: Rename rudder language and extension

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/19468

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Pull request merged**
