### PR TITLE
Fixes #22816: Use cargo vet to check Rust dependencies

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/22816

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by Fdall — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
