### PR TITLE
Fixes #23341: Rudderc transform some method parameter name in an incorrect manner

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/23341

### CODE REVIEW

**Comment by Fdall** [comment]
Commit modified

**Comment by amousset** [comment]
We should have an example in the tests

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Review by amousset — APPROVED** [review]

**Comment by amousset** [comment]
Perfect, well done!

**Comment by Fdall** [comment]
OK, squash merging this PR

**Pull request merged**
