### PR TITLE
Fixes #12206: Node details "properties" page broken: js not loading

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://www.rudder-project.org/redmine/issues/12206

### CODE REVIEW

**Comment by fanf** [comment]
I'm getting errors when trying to delete or add properties:

On the node details page (not sure it's linked): 
`jQuery.Deferred exception: scope is undefined @http://localhost:8082/rudder-web/secure/nodeManager/searchNodes#{%22nodeId%22:%22729be5c4-55a2-4b97-8529-5154cbb63a18%22,%22displayCompliance%22:false,%22query%22:{%22select%22:%22node%22,%22composition%22:%22And%22,%22where%22:[{%22objectType%22:%22node%22,%22attribute%22:%22OS%22,%22comparator%22:%22eq%22,%22value%22:%22Linux%22}]}}:71:11
j@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/jquery/jquery-3.1.0.min.js:2:29566
g/</k<@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/jquery/jquery-3.1.0.min.js:2:29882
 undefined
jquery-3.1.0.min.js:2:31135
TypeError: scope is undefined
[Learn More]`


And when clicking on delete: 
`Error: currentNodeId is not defined
$scope.deleteProperty@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/rudder/angular/nodeProperties.js:127:9
fn@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/angular/angular.min.js line 233 > Function:4:230
b@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/angular/angular.min.js:126:128
e@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/angular/angular.min.js:276:195
$eval@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/angular/angular.min.js:145:343
$apply@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/angular/angular.min.js:146:47
compile/</<@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/angular/angular.min.js:276:245
dispatch@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/jquery/jquery-3.1.0.min.js:3:9870
add/q.handle@http://localhost:8082/rudder-web/cache-4.3.0~beta2-SNAPSHOT/javascript/jquery/jquery-3.1.0.min.js:3:7932
angular.min.js:118:8
`

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
Yeah a last minute change, i thougt a variable was unused, readded it

**Comment by VinceMacBuche** [comment]
Works as expected

**Comment by fanf** [comment]
OK, merging this PR

**Pull request merged**
