### PR TITLE
Fixes #23212: N/A report message when a block expression is not valid is not rendered correctly

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/23212

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by ElaadF — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
