### PR TITLE
Fixes #20572: Update rust to 1.58.0

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/20572

### CODE REVIEW

**Comment by amousset** [comment]
we need to wait for docker image to be published

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Pull request merged**
