### PR TITLE
Fixes #18276: clean and refactor modules and folders

### PR DESCRIPTION
**Pull request by gpoblon**
https://issues.rudder.io/issues/18276

### CODE REVIEW

**Comment by gpoblon** [comment]
Commit modified

**Comment by gpoblon** [comment]
Commit modified

**Comment by gpoblon** [comment]
PR updated with a new commit

**Comment by gpoblon** [comment]
Commit modified

**Review by peckpeck — APPROVED** [review]

**Comment by gpoblon** [comment]
OK, squash merging this PR

**Pull request merged**
