### PR TITLE
Fixes #26000: 

### PR DESCRIPTION
**Pull request by clarktsiory**
https://issues.rudder.io/issues/26000
Make a `sanitizePath` util method in a new file utils namespace object. In the long term we may want to add other errors related to file handling (permissions,size), and also other security errors.
So we should have base types, and the returned error should be part of the return type.

### CODE REVIEW

**Comment by clarktsiory** [comment]
Commit modified

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Review by fanf — COMMENTED** [review]
The error should be an `AccessError` in error file.

**Comment by fanf** [comment]
`SecurityError` even

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Review by fanf — APPROVED** [review]
Cool !

**Comment by fanf** [comment]
Merging by hand because tests error are not linked to the PR

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
