### PR TITLE
Fixes #7609: Bad logger-test.xml output trace level message in tests

### PR DESCRIPTION
**Pull request by fanf**
https://www.rudder-project.org/redmine/issues/7609

### CODE REVIEW

**Comment by ncharles** [comment]
1000th Pull Requests ! 
AMAZING

**Comment by ncharles** [comment]
:1000:

**Comment by VinceMacBuche** [comment]
BEST PR EVER

I think, Someone opening the 1000th PR on a project should offer a bottle of champagne to all its coworker

**Comment by VinceMacBuche** [comment]
(unless I opened it)

**Pull request merged**
