### PR TITLE
Fixes #25866: After restart, nodes that were set back to default policy mode return to their previous overriden mode

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/25866

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by fanf** [comment]
Could you add a unit test in https://github.com/Normation/rudder/blob/master/webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scalascala ? Appart that, seems OK, can be self-merged once the test pass.

**Comment by VinceMacBuche** [comment]
Commit modified

**Review by fanf — APPROVED** [review]
LGTM

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Pull request merged**
