### PR TITLE
Fixes #22339: Hook timeout may not have the good value

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/22339

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
Commit modified

**Review by fanf — APPROVED** [review]
Lgtm, good catch for the variable order

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Pull request merged**
