### PR TITLE
Fixes #9354: Add a jumbotron next to Directives list

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://www.rudder-project.org/redmine/issues/9354

### CODE REVIEW

**Comment by RaphaelGauthier** [comment]
PR rebased

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
PR rebased

**Comment by RaphaelGauthier** [comment]
PR rebased

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by peckpeck** [comment]
This needs a retarget to 4.2 and a validation.

**Comment by RaphaelGauthier** [comment]
PR rebased

**Comment by RaphaelGauthier** [comment]
The interface has changed a lot since the last year. I close this PR to reopen one based on the interface of Rudder 4.2.

**Comment by RaphaelGauthier** [comment]
PR rebased

**Pull request closed without merging**
