### PR TITLE
Fixes #23763: Improve techniques tests

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/23763

- [x] Test conditions on Windows
- [x] Separate option for agent path (defaults to agent install dir)
- [x] Don't use a temp dir for test files. Use files prefixed by case name in target dir.
- [x] Use a sane and predictable dir for reports JSON output
- [x] Add an `export` subcommand to create archives for import into Rudder
- [x] Run PowerShell scripts in a way that detects errors
- [x] Remove trailing slash from Windows agent path (because...)
- [x] Update doc for Windows tests and export.

Still to be tested on Windows.

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by Fdall — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
