### PR TITLE
Fixes #20236: Make the rows of the compliance tables foldable to show more levels of compliance in Rules UI

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/20236

### CODE REVIEW

**Comment by RaphaelGauthier** [comment]
compliance-table-example

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
PR rebased

**Review by VinceMacBuche — APPROVED** [review]

**Comment by RaphaelGauthier** [comment]
Commit modified

**Pull request merged**
