### PR TITLE
Fixes #19938: Copy to clipboard button for user creation command in login page

### PR DESCRIPTION
**Pull request by ElaadF**
https://issues.rudder.io/issues/19938

### CODE REVIEW

**Comment by ElaadF** [comment]
Commit modified

**Comment by ElaadF** [comment]
Commit modified

**Comment by ElaadF** [comment]
Commit modified

**Comment by ElaadF** [comment]
PR rebased

**Comment by fanf** [comment]
Can you add a screenshot please ?

**Comment by ElaadF** [comment]
[](url)
cm_copy

**Review by fanf — APPROVED** [review]

**Pull request merged**
