### PR TITLE
Fixes #23721: Allow testing Windows techniques

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/23721

* Doesn't affect technique generation, should be safe
* Add a few things to the test case spec:
  * A `policy_mode` parameter. Also implemented it for Linux tests.
  * A `target` parameter, allowing to run on the right target.

A sad point:

* We need the .cf files for Windows methods in order to run the techniques on Windows.

This PR does not include:

* A way to reliably catch failures in PowerShell commands.
* Proper reportsFile management, is was not expected by the script in the agent so I made a hacky fallback.
* Proper path for JSON reports files. They are currently misplaced, I'll address this in a separate PR.
* Conditions defined before starting the technique. They are currently ignored on Windows.

Tested on Windows:

image

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR rebased

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by Fdall — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
