### PR TITLE
Fixes #4359: It is overly slow to show the list of Pending Review or Pending Deployment even if the number is 0

### PR DESCRIPTION
**Pull request by VinceMacBuche**
http://www.rudder-project.org/redmine/issues/4359

### CODE REVIEW

**Comment by fanf** [comment]
Could you try to remove methods from services/repositories that were used to make thing slow ? 
I'm not sure there are stull used, and we should force the future us to use the quick way.

**Comment by VinceMacBuche** [comment]
They are still used (only once when looking for one ochange request detailed info

**Comment by fanf** [comment]
OK

**Comment by fanf** [comment]
oups, bad button

**Pull request merged**
