### PR TITLE
Fixes #18511: Remove API v1 endpoints

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/18511

### CODE REVIEW

**Comment by fanf** [comment]
PR rebased

**Review by VinceMacBuche — APPROVED** [review]

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
OK, squash merging this PR

**Review by VinceMacBuche — APPROVED** [review]

**Comment by amousset** [comment]
:+1: for the API doc

**Comment by fanf** [comment]
PR rebased

**Pull request merged**
