### PR TITLE
Fixes #22072: Display compliance by directive

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/22072

### CODE REVIEW

**Comment by RaphaelGauthier** [comment]
directive-compliance

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by ElaadF** [comment]
PR rebased

**Comment by ElaadF** [comment]
See https://github.com/Normation/rudder/pull/4626 will the full functionnal PR (API + frontend)

**Pull request closed without merging**
