### PR TITLE
Fixes #22456: Change json structure returned for /settings/allowed_networks

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/22456

### CODE REVIEW

**Review by VinceMacBuche — APPROVED** [review]

**Comment by fanf** [comment]
PR rebased

**Comment by fanf** [comment]
Seems that an API version is missing: 
```13:50:17  [error] x correctly build an archive with past revision items
13:50:17  [error]  I got an error in test: Full(JsonResponsePrettify(JObject(List(JField(action,JString(unknow)), JField(id,JNothing), JField(result,JString(error)), JField(errorDetails,JString(Bad request: Request is missing a version but the version is required for 'GET api/archives/export'. Available versions: '16'17'18')))),List(),List(),500,true)) (ArchiveApiTest.scala:593)
13:50:17  [info] 
13:50:17  [info] 
13:50:17  [info] 
13:50:17  [info] Total for specification ArchiveApiTest
13:50:17  [info] Finished in 1 second, 416 ms
13:50:17  16 examples, 17 expectations, 11 failures, 5 errors
13:50:17  [info] 
13:50:17  Tests run: 16, Failures: 11, Errors: 5, Skipped: 0, Time elapsed: 3.545 sec <<< FAILURE!
13:50:17  when the feature switch is disabled, request should::error in GET /archives/export(com.normation.rudder.rest.ArchiveApiTest)  Time elapsed: 0.017 sec  <<< FAILURE!
13:50:17  java.lang.Exception: I got an error in test: Full(JsonResponsePrettify(JObject(List(JField(action,JString(unknow)), JField(id,JNothing), JField(result,JString(error)), JField(errorDetails,JString(Bad request: Request is missing a version but the version is required for 'GET api/archives/export'. Available versions: '16'17'18')))),List(),List(),500,true))
13:50:17  	at com.normation.rudder.rest.ArchiveApiTest.$anonfun$new$3(ArchiveApiTest.scala:117)
13:50:17  	at com.normation.rudder.rest.RestTest.$anonfun$execRequestResponse$1(RestTestSetUp.scala:1029)
13:50:17  	at net.liftweb.mockweb.MockWeb$.testReq(MockWeb.scala:106)
13:50:17  	at com.normation.rudder.rest.RestTest.$anonfun$doReq$2(RestTestSetUp.scala:1008)
13:50:17  	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
13:50:17  	at com.normation.rudder.rest.RestTest.$anonfun$doReq$1(RestTestSetUp.scala:1008)
13:50:17  	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
13:50:17  	at com.normation.rudder.rest.RestTest.doReq(RestTestSetUp.scala:1007)
13:50:17  	at com.normation.rudder.rest.RestTest.execRequestResponse(RestTestSetUp.scala:1019)
13:50:17  	at com.normation.rudder.rest.RestTest.testGETResponse(RestTestSetUp.scala:1099)
13:50:17  	at com.normation.rudder.rest.ArchiveApiTest.$anonfun$new$2(ArchiveApiTest.scala:114)```

**Review by amousset — APPROVED** [review]

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
