### PR TITLE
Fixes #18474: Width of the Directive tree changes according to the selected Directive.

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/18474

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
I think this file should only be included in healtcheck page

**Comment by VinceMacBuche** [comment]
and if some things a related to the notification, it should be in a separated file

**Comment by RaphaelGauthier** [comment]
You're right! I'm doing it

**Comment by RaphaelGauthier** [comment]
Commit modified

**Review by fanf — APPROVED** [review]

**Pull request merged**
