### PR TITLE
Fixes #11725: "Priority" level mean the contrary to what is thought

### PR DESCRIPTION
**Pull request by fanf**
https://www.rudder-project.org/redmine/issues/11725

### CODE REVIEW

**Comment by fanf** [comment]
PR rebased

**Comment by VinceMacBuche** [comment]
Ok to me, needs to be validated with @peckpeck

**Comment by amousset** [comment]
This is great!

**Comment by ncharles** [comment]
:heart:

**Comment by fanf** [comment]
OK, merging this PR

**Pull request merged**
