### PR TITLE
Fixes #11643: On Nodes table, put the link to node details on node's name instead of on magnifying glass icon

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://www.rudder-project.org/redmine/issues/11643

### CODE REVIEW

**Comment by amousset** [comment]
https://pics.me.me/its-over-its-finally-over-26367283.png

**Comment by VinceMacBuche** [comment]
@amousset It was such a good UX feature why do we remove it :( :( :(

**Comment by RaphaelGauthier** [comment]
all good thing comes to an end... :)

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Pull request merged**
