### PR TITLE
Fixes #18818: Update relayd to tokio 1.0

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/18818

### CODE REVIEW

**Comment by amousset** [comment]
PR rebased

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
Still waiting for `reqwest` release.

**Review by gpoblon — APPROVED** [review]

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
