### PR TITLE
Fixes #25767: Create a variant of API token file with curl header parameter syntax

### PR DESCRIPTION
**Pull request by clarktsiory**
https://issues.rudder.io/issues/25767

Factorizing the `X-API-Token` header definition, and creating an additional headers file (the betterfiles API is also useful to create and dispose files in tests)

### CODE REVIEW

**Comment by clarktsiory** [comment]
Commit modified

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Review by amousset — APPROVED** [review]

**Comment by clarktsiory** [comment]
OK, squash merging this PR

**Comment by clarktsiory** [comment]
OK, merging this PR

**Pull request merged**
