### PR TITLE
Fixes #22209: Dynamic group logs must not be conflated with scheduled job ones

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/22209

### CODE REVIEW

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
