### PR TITLE
Fixes #19675: Restart HTTP clients when configuration changes

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/19675

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by ncharles — APPROVED** [review]
Great PR

**Pull request merged**
