### PR TITLE
Fixes #23525: Document in logback.xml loggers that display secret at debug level 

### PR DESCRIPTION
**Pull request by clarktsiory**
https://issues.rudder.io/issues/23525

### CODE REVIEW

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Review by fanf — APPROVED** [review]
LGTM !

Congrats on your first PR @rudderio \o/

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
